project:
  type: website

website:
  title: "SmartHab Workshop 2022"
  navbar:
    type: dark
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: agenda.qmd
        text: Agenda

format:
  html:
    theme: lux 
    css: styles.css
    toc: true
