project:
  type: website

website:
  title: "SmartHab Workshop 2022"
  navbar:
    type: dark
    background: primary
    left:
      - href: landing.qmd
        text: Home

format:
  html:
    theme: lux 
    css: styles.css
    toc: true
