---
title: "First International Workshop on Interdisciplinary Paradigms for Semi-Autonomous Deep-Space Habitation"
---

## Workshop Date

**13-14 October, 2022**

## Workshop Location

**University of Texas San Antonio, Downtown**

## Workshop Objectives

* Identify and strengthen the growing community of researchers, developers, investors, and users of future deep-space habitats
* Provide a broad educational and networking experience for the over 100 graduate and undergraduate students that are playing essential roles in the two NASA-sponsored Space Technology research institutes 
* Gain insight and updates regarding NASA's space habitat development efforts 
* Discuss commercial space partners' space habitat designs, subsystem requirements, and new-technology needs from the SmartHabs research community
* Present updates of research status from both the RETH and HOME Institutes
* Foster collaboration and co-education between NASA, spaceflight industry, and the two SmartHabs research institutes

## Details

Attendees and presenters will consist of NASA subject matter experts, astronauts, space industry leaders, university researchers, and PIs and students from the SmartHabs Institutes. 

Though the workshop will not have proceedings or a formal peer-review procedure, we will require 1-page abstract/position paper submissions from participants. These abstracts will be reviewed to develop the program and allocate oral, poster and panel presentations of the work being discussed. 

:::{.callout-warning}
### Abstract Deadline
Abstracts are due ~~August 29, 2022~~ September 23, so please plan accordingly.
:::

## Registration

You can now register for the event by following this link: [https://smarthab2022.eventbrite.com](https://smarthab2022.eventbrite.com)

:::{.callout-important}
### Registration Deadline
Given that we need to provide a final headcount to our catering provider, there is a hard deadline for registration: September 23, 2022.
:::

## Abstract Submission

You can now submit an abstract by following this link: [https://cmt3.research.microsoft.com/SMARTHAB2022](https://cmt3.research.microsoft.com/SMARTHAB2022)

## Travel and Lodging

We have reserved some rooms at the DobuleTree by Hilton very close to where we will have the workshop. You can use [this link](https://www.hilton.com/en/book/reservation/rooms/?ctyhocn=SATDWDT&arrivalDate=2022-10-12&departureDate=2022-10-14&groupCode=CDTUTC&room1NumAdults=1&cid=OM%2CWW%2CHILTONLINK%2CEN%2CDirectLink) to book a room. 

## Agenda 

We will keep a continuously evolving agenda for the event [here](agenda.html).  

## Poster Details

If your abstract was accepted for poster presentation, please prepare a 18" wide x 24" tall poster and bring it with you. We will provide easels and poster boards. 

## Organizing Team

For any questions or comments, please reach out to the co-chairs of the workshop:

* [Dawn Whitaker](mailto:dwhitaker@purdue.edu), Purdue University
* [Mario Bergés](mailto:marioberges@cmu.edu), Carnegie Mellon University
